### ISSUE TITLE
Sparkle 1.1 map crashes BWEM

### ISSUE THREAD

**Issue by kant2002** [N00byEdge/BWEM-community#23]
as reported, just running Sparkle on 1.1 map lead to crashing of the bot.
There proposal to fix this issue #19, but from first glance this is oversimplification which indicate that somehow `nullptr` is passed inside areas blocks. Root cause for this should be found. Once found proper fix could be applied. Thatnks @Cmccrave for reporting

**Comment by kant2002** [comment]
Ok. I now found the issue for crashing Zerg_Lair is the reason. That means we have building which is assigned to neutral player. Current BWEM implementation assumed to create StaticBuilding as buildings which are either special building, or Special_Pit_Door or Special_Right_Pit_Door

**Comment by kant2002** [comment]
Another observation, I open Sparkle 1.1 in the latest Starcraft Editor and it complain that 12 dodads was obsolete and 13 units was incorrectly placed. This is could be indication of why BWEM behave badly. I still not fully understand what's going on, but I see that some Neutral elements could be placed incorrectly. Trying to understand kind of units which BWEM could not chew. 

After opening map in the editor and resave, the map correctly processed by BWEM

**Comment by kant2002** [comment]
I finally able to confirm that one of the issues with Sparkle is that it contains two mineral patches which overlap each other.

**Comment by kant2002** [comment]
I verify behavior in the 1.16.1 and the game display both mineral patches, even if they are overlapped.

**Comment by kant2002** [comment]
Another issue with Sparkle 1.1. is that walk positions (7,436), (478,155) and (211,23) does not belongs to any area.

**Comment by Cmccrave** [comment]
Are those the corners of the map by chance?

**Comment by kant2002** [comment]
No, middle of the map. This locations overlapped by special buildings

**Comment by kant2002** [comment]
![image](https://user-images.githubusercontent.com/4257079/40313521-d5289070-5d37-11e8-8065-5550d33f3e02.png)
Example how mineral patches overlapped.

Approximate location of one of the walk positions which does not belongs to any area
![image](https://user-images.githubusercontent.com/4257079/40313560-f517ee9e-5d37-11e8-8c3d-47a1ff5a442c.png)

**Comment by kant2002** [comment]
Another potential issue, is that some Vespene Geysers is overlapped by Sprites. This is geysers covered by pictires. Bottom right corner of the map. Try to spot Geyser here
![image](https://user-images.githubusercontent.com/4257079/40313910-bdaff6e4-5d38-11e8-8d0c-2bf0c05ee42a.png)

**Comment by MicroDK** [comment]
It does not crash on Sparkle anymore... :)

**Comment by MicroDK** [comment]
This fix also fixed crash on Gold Rush and the issue can be closed. :-)
